import { useEffect,useState } from 'react';
import { api } from '../../lib/api';
import { Empty,Panel } from '../../components/StateViews';

type LinkDraft={slug:string;destinationPath:string;source:string;medium:string;content:string;campaignId:string};
const initial:LinkDraft={slug:'',destinationPath:'/eventos/',source:'instagram',medium:'social',content:'',campaignId:''};
const defaultPopup={enabled:true,frequency:'session',delayMs:700,selectedEventId:'',maxEvents:4};
export function Marketing(){
  const [links,setLinks]=useState<any[]>([]);const [campaigns,setCampaigns]=useState<any[]>([]);const [events,setEvents]=useState<any[]>([]);const [draft,setDraft]=useState<LinkDraft>(initial);const [message,setMessage]=useState('');const [popup,setPopup]=useState<any>(defaultPopup);const [campaignName,setCampaignName]=useState('');
  const load=async()=>{const [l,c,e,s]=await Promise.all([api<any>('/api/admin/tracking-links'),api<any>('/api/admin/campaigns'),api<any>('/api/admin/events'),api<any>('/api/admin/settings')]);setLinks(l.results||[]);setCampaigns(c.results||[]);setEvents(e.results||[]);const row=(s.results||[]).find((x:any)=>x.key==='event_popup');if(row){try{setPopup({...defaultPopup,...JSON.parse(row.value_json)})}catch{setPopup(defaultPopup)}}};
  useEffect(()=>{load().catch(()=>{});},[]);
  const set=(key:keyof LinkDraft,value:string)=>setDraft(d=>({...d,[key]:value}));
  const create=async()=>{setMessage('');try{const result=await api<any>('/api/admin/tracking-links',{method:'POST',body:JSON.stringify({...draft,campaignId:draft.campaignId||null})});setMessage(`Criado: ${result.url}`);setDraft(initial);load();}catch(e:any){setMessage(e.message)}};
  const savePopup=async()=>{await api('/api/admin/settings/event_popup',{method:'PUT',body:JSON.stringify({...popup,selectedEventId:popup.selectedEventId||null,delayMs:Number(popup.delayMs),maxEvents:Number(popup.maxEvents)})});setMessage('Configuração do popup salva.');};
  const createCampaign=async()=>{if(!campaignName.trim())return;await api('/api/admin/campaigns',{method:'POST',body:JSON.stringify({name:campaignName.trim(),status:'active'})});setCampaignName('');setMessage('Campanha criada.');load()};
  return <Panel title="Marketing" eyebrow="Campanhas e aquisição">
    <div className="feature-cards"><article><strong>Popups</strong><p>Controlados pelo painel e exibidos somente quando há eventos ativos.</p></article><article><strong>Links rastreáveis</strong><p>Crie /r/influencer, /r/parceiro e acompanhe a origem até a conversão.</p></article><article><strong>Campanhas</strong><p>Agrupe links, UTMs e resultados em uma única campanha.</p></article></div>
    <div className="editor-section"><div className="editor-section-head"><div><h4>Popup de eventos</h4><small className="muted">Cidade sempre fica em destaque no site público.</small></div><button className="primary" onClick={savePopup}>Salvar popup</button></div><div className="form-grid"><label className="toggle"><input type="checkbox" checked={Boolean(popup.enabled)} onChange={e=>setPopup((p:any)=>({...p,enabled:e.target.checked}))}/> Ativar popup</label><label><span>Frequência</span><select value={popup.frequency} onChange={e=>setPopup((p:any)=>({...p,frequency:e.target.value}))}><option value="session">1 vez por sessão</option><option value="day">1 vez por dia</option><option value="always">Sempre que entrar</option></select></label><label><span>Atraso para abrir (ms)</span><input type="number" min="0" max="15000" value={popup.delayMs} onChange={e=>setPopup((p:any)=>({...p,delayMs:Number(e.target.value)}))}/></label><label><span>Máximo de eventos</span><input type="number" min="1" max="6" value={popup.maxEvents} onChange={e=>setPopup((p:any)=>({...p,maxEvents:Number(e.target.value)}))}/></label><label className="wide"><span>Evento específico</span><select value={popup.selectedEventId||''} onChange={e=>setPopup((p:any)=>({...p,selectedEventId:e.target.value}))}><option value="">Todos os eventos ativos</option>{events.filter(e=>['published','sales_open','sold_out'].includes(e.status)).map(e=><option key={e.id} value={e.id}>{e.title||e.slug} · {e.city}{e.state?' / '+e.state:''}</option>)}</select></label></div></div>
    <div className="editor-section"><div className="editor-section-head"><h4>Campanhas</h4></div><div className="row-actions"><input value={campaignName} onChange={e=>setCampaignName(e.target.value)} placeholder="Ex.: Halloween Recife — Instagram"/><button className="primary" onClick={createCampaign}>Criar campanha</button></div>{campaigns.length?<div className="stack-list" style={{marginTop:12}}>{campaigns.map(c=><article className="stack-item" key={c.id}><div><strong>{c.name}</strong><small>{c.status} · {c.id}</small></div></article>)}</div>:<p className="muted">Nenhuma campanha criada.</p>}</div>
    <div className="create-form tracking-form"><h3>Novo link rastreável</h3><div className="form-grid"><label><span>Slug</span><input value={draft.slug} onChange={e=>set('slug',e.target.value)} placeholder="delicias-colombianas"/></label><label><span>Destino</span><input value={draft.destinationPath} onChange={e=>set('destinationPath',e.target.value)} placeholder="/eventos/el-perreo-de-mas-alla"/></label><label><span>Origem</span><input value={draft.source} onChange={e=>set('source',e.target.value)} placeholder="instagram"/></label><label><span>Meio</span><input value={draft.medium} onChange={e=>set('medium',e.target.value)} placeholder="social"/></label><label><span>Identificação</span><input value={draft.content} onChange={e=>set('content',e.target.value)} placeholder="parceiro-x"/></label><label><span>Campanha</span><select value={draft.campaignId} onChange={e=>set('campaignId',e.target.value)}><option value="">Sem campanha</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><div className="editor-footer"><span>{message}</span><button className="primary" onClick={create}>Gerar link</button></div></div>
    {links.length?<div className="list">{links.map(link=><article key={link.id}><div><strong>/r/{link.slug}</strong><span>{link.source} · {link.medium}{link.campaign_name?' · '+link.campaign_name:''} → {link.destination_path}</span></div><div className="link-stats"><b>{link.click_count||0}</b><small>cliques</small></div></article>)}</div>:<Empty>Nenhum link rastreável ainda.</Empty>}
  </Panel>;
}
