import { useEffect,useMemo,useState } from 'react';
import { api } from '../../lib/api';
import { Panel,Empty } from '../../components/StateViews';
import { MediaPicker } from '../../components/MediaPicker';

type Draft={slug:string;city:string;state:string;startsAt:string;endsAt:string;venueName:string;titlePt:string;titleEs:string};
const empty:Draft={slug:'',city:'',state:'',startsAt:'',endsAt:'',venueName:'',titlePt:'',titleEs:''};
type Tab='general'|'content'|'visual'|'tickets'|'artists'|'history';

function locMap(rows:any[]=[]){const out:Record<string,any>={};for(const row of rows)out[row.locale]={title:row.title||'',summary:row.summary||'',description:row.description||'',seoTitle:row.seo_title||'',seoDescription:row.seo_description||''};return out;}
function parseTheme(value:string){try{return JSON.parse(value||'{}')}catch{return {}}}

export function Events(){
  const [items,setItems]=useState<any[]>([]);const [creating,setCreating]=useState(false);const [draft,setDraft]=useState<Draft>(empty);const [message,setMessage]=useState('');
  const [detail,setDetail]=useState<any|null>(null);const [tab,setTab]=useState<Tab>('general');const [busy,setBusy]=useState(false);const [revisions,setRevisions]=useState<any[]>([]);
  const [ticketDraft,setTicketDraft]=useState({name:'',price:'',salesUrl:'',status:'active'});const [artistDraft,setArtistDraft]=useState({name:'',role:'',instagramUrl:'',mediaId:null as string|null});
  const load=()=>api<any>('/api/admin/events').then(r=>setItems(r.results||[])).catch(()=>{});
  useEffect(()=>{load();},[]);
  const set=(key:keyof Draft,value:string)=>setDraft(d=>({...d,[key]:value}));
  const create=async()=>{setMessage('');try{await api('/api/admin/events',{method:'POST',body:JSON.stringify({slug:draft.slug,city:draft.city,state:draft.state||undefined,startsAt:draft.startsAt,endsAt:draft.endsAt||undefined,venueName:draft.venueName||undefined,locales:{'pt-BR':{title:draft.titlePt||draft.slug},es:{title:draft.titleEs||draft.titlePt||draft.slug}}})});setDraft(empty);setCreating(false);setMessage('Evento criado como rascunho.');load();}catch(e:any){setMessage(e.message)}};
  const open=async(id:string)=>{const data=await api<any>(`/api/admin/events/${id}`);setDetail({...data,locales:locMap(data.localizations),theme:parseTheme(data.event.theme_json)});setTab('general');loadRevisions(id)};
  const loadDetail=async(id:string)=>{const data=await api<any>(`/api/admin/events/${id}`);setDetail({...data,locales:locMap(data.localizations),theme:parseTheme(data.event.theme_json)});};
  const loadRevisions=(id:string)=>api<any>(`/api/admin/events/${id}/revisions`).then(r=>setRevisions(r.results||[])).catch(()=>setRevisions([]));
  const patchEvent=(patch:Record<string,any>)=>setDetail((d:any)=>({...d,event:{...d.event,...patch}}));
  const patchLocale=(locale:string,patch:Record<string,any>)=>setDetail((d:any)=>({...d,locales:{...d.locales,[locale]:{...(d.locales?.[locale]||{}),...patch}}}));
  const saveCore=async()=>{if(!detail)return;setBusy(true);setMessage('');try{const e=detail.event;await api(`/api/admin/events/${e.id}`,{method:'PATCH',body:JSON.stringify({slug:e.slug,status:e.status,city:e.city,state:e.state,country:e.country,venueName:e.venue_name,venueAddress:e.venue_address,startsAt:e.starts_at,endsAt:e.ends_at,heroMediaId:e.hero_media_id,logoMediaId:e.logo_media_id,theme:detail.theme,locales:detail.locales})});setMessage('Evento salvo.');await loadDetail(e.id);await loadRevisions(e.id);load();}catch(err:any){setMessage(err.message)}finally{setBusy(false)}};
  const addTicket=async()=>{if(!detail||!ticketDraft.name)return;await api(`/api/admin/events/${detail.event.id}/tickets`,{method:'POST',body:JSON.stringify({name:ticketDraft.name,priceCents:ticketDraft.price?Math.round(Number(ticketDraft.price)*100):null,salesUrl:ticketDraft.salesUrl||null,status:ticketDraft.status,position:detail.tickets.length})});setTicketDraft({name:'',price:'',salesUrl:'',status:'active'});await loadDetail(detail.event.id);await loadRevisions(detail.event.id)};
  const addArtist=async()=>{if(!detail||!artistDraft.name)return;await api(`/api/admin/events/${detail.event.id}/artists`,{method:'POST',body:JSON.stringify({name:artistDraft.name,role:artistDraft.role||null,instagramUrl:artistDraft.instagramUrl||null,mediaId:artistDraft.mediaId,position:detail.artists.length})});setArtistDraft({name:'',role:'',instagramUrl:'',mediaId:null});await loadDetail(detail.event.id);await loadRevisions(detail.event.id)};
  const restore=async(revisionId:string)=>{if(!detail||!confirm('Restaurar esta versão do evento? O estado atual também será preservado no histórico.'))return;await api(`/api/admin/events/${detail.event.id}/revisions/${revisionId}/restore`,{method:'POST'});await loadDetail(detail.event.id);await loadRevisions(detail.event.id);setMessage('Versão restaurada.');load();};

  if(detail){const e=detail.event;const pt=detail.locales?.['pt-BR']||{};const es=detail.locales?.es||{};return <Panel title={pt.title||e.slug} eyebrow="Gerenciar evento" action={<button onClick={()=>{setDetail(null);setMessage('')}}>Voltar aos eventos</button>}>
    <div className="event-manager"><nav className="event-manager-nav">{([['general','Geral'],['content','PT / ES'],['visual','Identidade'],['tickets','Ingressos'],['artists','Artistas'],['history','Histórico']] as [Tab,string][]).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="event-manager-body">
      {tab==='general'&&<><h3>Informações gerais</h3><div className="form-grid"><label><span>Slug</span><input value={e.slug||''} onChange={x=>patchEvent({slug:x.target.value})}/></label><label><span>Status</span><select value={e.status} onChange={x=>patchEvent({status:x.target.value})}><option value="draft">Rascunho</option><option value="scheduled">Agendado</option><option value="published">Publicado</option><option value="sales_open">Vendas abertas</option><option value="sold_out">Esgotado</option><option value="finished">Realizado</option><option value="archived">Arquivado</option></select></label><label><span>Cidade</span><input value={e.city||''} onChange={x=>patchEvent({city:x.target.value})}/></label><label><span>UF</span><input value={e.state||''} onChange={x=>patchEvent({state:x.target.value})}/></label><label><span>Local</span><input value={e.venue_name||''} onChange={x=>patchEvent({venue_name:x.target.value})}/></label><label><span>Endereço</span><input value={e.venue_address||''} onChange={x=>patchEvent({venue_address:x.target.value})}/></label><label><span>Início</span><input type="datetime-local" value={(e.starts_at||'').slice(0,16)} onChange={x=>patchEvent({starts_at:x.target.value})}/></label><label><span>Fim</span><input type="datetime-local" value={(e.ends_at||'').slice(0,16)} onChange={x=>patchEvent({ends_at:x.target.value})}/></label></div></>}
      {tab==='content'&&<><h3>Conteúdo bilíngue</h3><div className="locale-grid"><div className="locale-editor"><h4>Português</h4><label className="field"><span>Título</span><input value={pt.title||''} onChange={x=>patchLocale('pt-BR',{title:x.target.value})}/></label><label className="field"><span>Resumo</span><textarea value={pt.summary||''} onChange={x=>patchLocale('pt-BR',{summary:x.target.value})}/></label><label className="field"><span>Descrição</span><textarea value={pt.description||''} onChange={x=>patchLocale('pt-BR',{description:x.target.value})}/></label><label className="field"><span>SEO title</span><input value={pt.seoTitle||''} onChange={x=>patchLocale('pt-BR',{seoTitle:x.target.value})}/></label><label className="field"><span>SEO description</span><textarea value={pt.seoDescription||''} onChange={x=>patchLocale('pt-BR',{seoDescription:x.target.value})}/></label></div><div className="locale-editor"><h4>Español</h4><label className="field"><span>Título</span><input value={es.title||''} onChange={x=>patchLocale('es',{title:x.target.value})}/></label><label className="field"><span>Resumen</span><textarea value={es.summary||''} onChange={x=>patchLocale('es',{summary:x.target.value})}/></label><label className="field"><span>Descripción</span><textarea value={es.description||''} onChange={x=>patchLocale('es',{description:x.target.value})}/></label><label className="field"><span>SEO title</span><input value={es.seoTitle||''} onChange={x=>patchLocale('es',{seoTitle:x.target.value})}/></label><label className="field"><span>SEO description</span><textarea value={es.seoDescription||''} onChange={x=>patchLocale('es',{seoDescription:x.target.value})}/></label></div></div></>}
      {tab==='visual'&&<><h3>Identidade da edição</h3><div className="theme-grid"><MediaPicker label="Imagem principal" value={e.hero_media_id} onChange={id=>patchEvent({hero_media_id:id})}/><MediaPicker label="Logo do evento" value={e.logo_media_id} onChange={id=>patchEvent({logo_media_id:id})}/><label className="field"><span>Cor principal</span><input type="color" value={detail.theme?.primary||'#ff1a12'} onChange={x=>setDetail((d:any)=>({...d,theme:{...d.theme,primary:x.target.value}}))}/></label><label className="field"><span>Fundo</span><input type="color" value={detail.theme?.background||'#080808'} onChange={x=>setDetail((d:any)=>({...d,theme:{...d.theme,background:x.target.value}}))}/></label><label className="field"><span>Texto</span><input type="color" value={detail.theme?.foreground||'#fffdf8'} onChange={x=>setDetail((d:any)=>({...d,theme:{...d.theme,foreground:x.target.value}}))}/></label></div><p className="hint">O tema define tokens permitidos. CSS ou JavaScript arbitrário nunca é salvo pelo painel.</p></>}
      {tab==='tickets'&&<><div className="editor-section-head"><h3>Ingressos</h3></div><div className="editor-section"><div className="form-grid"><label><span>Nome / lote</span><input value={ticketDraft.name} onChange={x=>setTicketDraft(v=>({...v,name:x.target.value}))}/></label><label><span>Preço (R$)</span><input type="number" min="0" step="0.01" value={ticketDraft.price} onChange={x=>setTicketDraft(v=>({...v,price:x.target.value}))}/></label><label><span>Link de venda</span><input value={ticketDraft.salesUrl} onChange={x=>setTicketDraft(v=>({...v,salesUrl:x.target.value}))}/></label><label><span>Status</span><select value={ticketDraft.status} onChange={x=>setTicketDraft(v=>({...v,status:x.target.value}))}><option value="active">Ativo</option><option value="draft">Rascunho</option><option value="sold_out">Esgotado</option><option value="closed">Encerrado</option></select></label></div><button className="primary" onClick={addTicket}>Adicionar ingresso</button></div><div className="stack-list">{detail.tickets.map((t:any)=><article className="stack-item" key={t.id}><div><strong>{t.name}</strong><small>{t.price_cents==null?'Preço não informado':`R$ ${(t.price_cents/100).toFixed(2)}`} · {t.status}</small></div><div className="stack-actions"><button onClick={async()=>{await api(`/api/admin/events/${e.id}/tickets/${t.id}`,{method:'PATCH',body:JSON.stringify({status:t.status==='active'?'closed':'active'})});loadDetail(e.id);loadRevisions(e.id)}}>{t.status==='active'?'Encerrar':'Ativar'}</button><button onClick={async()=>{if(confirm('Excluir este ingresso?')){await api(`/api/admin/events/${e.id}/tickets/${t.id}`,{method:'DELETE'});loadDetail(e.id);loadRevisions(e.id)}}}>Excluir</button></div></article>)}</div></>}
      {tab==='artists'&&<><h3>Line-up / artistas</h3><div className="editor-section"><div className="form-grid"><label><span>Nome</span><input value={artistDraft.name} onChange={x=>setArtistDraft(v=>({...v,name:x.target.value}))}/></label><label><span>Função</span><input value={artistDraft.role} onChange={x=>setArtistDraft(v=>({...v,role:x.target.value}))} placeholder="DJ / atração"/></label><label><span>Instagram</span><input value={artistDraft.instagramUrl} onChange={x=>setArtistDraft(v=>({...v,instagramUrl:x.target.value}))}/></label><MediaPicker label="Foto" value={artistDraft.mediaId} onChange={id=>setArtistDraft(v=>({...v,mediaId:id}))}/></div><button className="primary" onClick={addArtist}>Adicionar artista</button></div><div className="stack-list">{detail.artists.map((a:any)=><article className="stack-item" key={a.id}><div><strong>{a.name}</strong><small>{a.role||'Artista'}{a.instagram_url?` · ${a.instagram_url}`:''}</small></div><div className="stack-actions"><button onClick={async()=>{if(confirm('Remover este artista?')){await api(`/api/admin/events/${e.id}/artists/${a.id}`,{method:'DELETE'});loadDetail(e.id);loadRevisions(e.id)}}}>Remover</button></div></article>)}</div></>}
      {tab==='history'&&<><h3>Histórico de versões</h3><p className="hint">Antes de alterações estruturais o estado do evento é preservado. Restaurar uma versão cria também um backup do estado atual.</p><div className="revision-list">{revisions.length?revisions.map((r:any)=><article key={r.id}><div><strong>Versão salva</strong><small>{new Date(r.created_at).toLocaleString('pt-BR')}</small></div><button onClick={()=>restore(r.id)}>Restaurar</button></article>):<Empty>Nenhuma versão anterior ainda.</Empty>}</div></>}
      {tab!=='tickets'&&tab!=='artists'&&tab!=='history'&&<div className="editor-footer"><span>{message}</span><button className="primary" disabled={busy} onClick={saveCore}>{busy?'Salvando…':'Salvar alterações'}</button></div>}
    </div></div>
  </Panel>}

  return <Panel title="Eventos" eyebrow="Agenda" action={<button className="primary" onClick={()=>setCreating(v=>!v)}>{creating?'Cancelar':'Criar evento'}</button>}>
    {creating&&<div className="create-form"><div className="form-grid"><label><span>Slug</span><input value={draft.slug} onChange={e=>set('slug',e.target.value)} placeholder="el-perreo-de-mas-alla"/></label><label><span>Cidade</span><input value={draft.city} onChange={e=>set('city',e.target.value)} placeholder="Recife"/></label><label><span>UF</span><input value={draft.state} onChange={e=>set('state',e.target.value)} placeholder="PE"/></label><label><span>Local</span><input value={draft.venueName} onChange={e=>set('venueName',e.target.value)} placeholder="Nome da casa"/></label><label><span>Início</span><input type="datetime-local" value={draft.startsAt} onChange={e=>set('startsAt',e.target.value)}/></label><label><span>Fim</span><input type="datetime-local" value={draft.endsAt} onChange={e=>set('endsAt',e.target.value)}/></label><label><span>Título PT</span><input value={draft.titlePt} onChange={e=>set('titlePt',e.target.value)}/></label><label><span>Título ES</span><input value={draft.titleEs} onChange={e=>set('titleEs',e.target.value)}/></label></div><div className="editor-footer"><span>{message}</span><button className="primary" onClick={create}>Criar rascunho</button></div></div>}
    {!creating&&message&&<p className="hint">{message}</p>}
    {items.length?<div className="list">{items.map(e=><article key={e.id}><div><strong>{e.title||e.slug}</strong><span>{e.city}{e.state?' · '+e.state:''} · {e.status}</span></div><div className="row-actions"><select value={e.status} onChange={async ev=>{await api(`/api/admin/events/${e.id}`,{method:'PATCH',body:JSON.stringify({status:ev.target.value})});load();}}><option value="draft">Rascunho</option><option value="scheduled">Agendado</option><option value="published">Publicado</option><option value="sales_open">Vendas abertas</option><option value="sold_out">Esgotado</option><option value="finished">Realizado</option><option value="archived">Arquivado</option></select><button onClick={()=>open(e.id)}>Gerenciar</button></div></article>)}</div>:<Empty>Nenhum evento no novo banco ainda.</Empty>}
  </Panel>;
}
