import { useEffect,useState } from 'react';
import { api } from '../../lib/api';
import { Panel,Empty } from '../../components/StateViews';
import { MediaPicker } from '../../components/MediaPicker';

type Tab='team'|'freelancers';
const emptyMember={name:'',roleKey:'',instagramUrl:'',position:0,mediaId:null as string|null,locales:{'pt-BR':{roleLabel:'',bio:''},es:{roleLabel:'',bio:''}}};

export function People(){
  const [tab,setTab]=useState<Tab>('team');const [team,setTeam]=useState<any[]>([]);const [freelancers,setFreelancers]=useState<any[]>([]);const [draft,setDraft]=useState<any>(emptyMember);const [creating,setCreating]=useState(false);const [message,setMessage]=useState('');
  const loadTeam=()=>api<any>('/api/admin/team').then(r=>setTeam(r.results||[])).catch(()=>{});
  const loadFreelancers=()=>api<any>('/api/admin/freelancers').then(r=>setFreelancers(r.results||[])).catch(()=>{});
  useEffect(()=>{loadTeam();loadFreelancers();},[]);
  const patchMember=(id:string,patch:any)=>setTeam(list=>list.map(x=>x.id===id?{...x,...patch}:x));
  const patchMemberLocale=(id:string,locale:string,patch:any)=>setTeam(list=>list.map(x=>x.id===id?{...x,locales:{...x.locales,[locale]:{...(x.locales?.[locale]||{}),...patch}}}:x));
  const saveMember=async(m:any)=>{await api(`/api/admin/team/${m.id}`,{method:'PATCH',body:JSON.stringify({name:m.name,roleKey:m.role_key,instagramUrl:m.instagram_url,position:m.position,mediaId:m.media_id,active:Boolean(m.active),locales:m.locales})});setMessage('Pessoa salva.');loadTeam()};
  const createMember=async()=>{if(!draft.name)return;await api('/api/admin/team',{method:'POST',body:JSON.stringify(draft)});setDraft(emptyMember);setCreating(false);setMessage('Pessoa adicionada à equipe.');loadTeam()};
  const updateFreelancer=async(id:string,status:string)=>{await api(`/api/admin/freelancers/${id}`,{method:'PATCH',body:JSON.stringify({status})});loadFreelancers()};
  return <Panel title="Pessoas" eyebrow="Equipe e freelancers" action={tab==='team'?<button className="primary" onClick={()=>setCreating(v=>!v)}>{creating?'Cancelar':'Adicionar pessoa'}</button>:undefined}>
    <div className="subnav"><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}>Equipe</button><button className={tab==='freelancers'?'active':''} onClick={()=>setTab('freelancers')}>Freelancers <span>{freelancers.filter(x=>x.status==='new').length}</span></button></div>
    {message&&<p className="hint">{message}</p>}
    {tab==='team'&&<>
      {creating&&<div className="create-form"><div className="form-grid"><label><span>Nome</span><input value={draft.name} onChange={e=>setDraft((d:any)=>({...d,name:e.target.value}))}/></label><label><span>Função interna</span><input value={draft.roleKey} onChange={e=>setDraft((d:any)=>({...d,roleKey:e.target.value}))}/></label><label><span>Instagram</span><input value={draft.instagramUrl} onChange={e=>setDraft((d:any)=>({...d,instagramUrl:e.target.value}))}/></label><label><span>Ordem</span><input type="number" value={draft.position} onChange={e=>setDraft((d:any)=>({...d,position:Number(e.target.value)}))}/></label><MediaPicker label="Foto" value={draft.mediaId} onChange={id=>setDraft((d:any)=>({...d,mediaId:id}))}/><label><span>Cargo PT</span><input value={draft.locales['pt-BR'].roleLabel} onChange={e=>setDraft((d:any)=>({...d,locales:{...d.locales,'pt-BR':{...d.locales['pt-BR'],roleLabel:e.target.value}}}))}/></label><label className="wide"><span>Bio PT</span><textarea value={draft.locales['pt-BR'].bio} onChange={e=>setDraft((d:any)=>({...d,locales:{...d.locales,'pt-BR':{...d.locales['pt-BR'],bio:e.target.value}}}))}/></label><label><span>Cargo ES</span><input value={draft.locales.es.roleLabel} onChange={e=>setDraft((d:any)=>({...d,locales:{...d.locales,es:{...d.locales.es,roleLabel:e.target.value}}}))}/></label><label className="wide"><span>Bio ES</span><textarea value={draft.locales.es.bio} onChange={e=>setDraft((d:any)=>({...d,locales:{...d.locales,es:{...d.locales.es,bio:e.target.value}}}))}/></label></div><button className="primary" onClick={createMember}>Adicionar à equipe</button></div>}
      {team.length?<div className="stack-list">{team.map(m=><article className="editor-section" key={m.id}><div className="editor-section-head"><div><strong>{m.name}</strong><small className="muted">posição {m.position} · {m.active?'visível':'oculto'}</small></div><div className="stack-actions"><button onClick={()=>patchMember(m.id,{active:m.active?0:1})}>{m.active?'Ocultar':'Exibir'}</button><button className="primary" onClick={()=>saveMember(m)}>Salvar</button><button onClick={async()=>{if(confirm(`Remover ${m.name} da equipe?`)){await api(`/api/admin/team/${m.id}`,{method:'DELETE'});loadTeam()}}}>Excluir</button></div></div><div className="form-grid"><label><span>Nome</span><input value={m.name||''} onChange={e=>patchMember(m.id,{name:e.target.value})}/></label><label><span>Função interna</span><input value={m.role_key||''} onChange={e=>patchMember(m.id,{role_key:e.target.value})}/></label><label><span>Instagram</span><input value={m.instagram_url||''} onChange={e=>patchMember(m.id,{instagram_url:e.target.value})}/></label><label><span>Ordem</span><input type="number" value={m.position||0} onChange={e=>patchMember(m.id,{position:Number(e.target.value)})}/></label><MediaPicker label="Foto" value={m.media_id} onChange={id=>patchMember(m.id,{media_id:id})}/><label><span>Cargo PT</span><input value={m.locales?.['pt-BR']?.roleLabel||''} onChange={e=>patchMemberLocale(m.id,'pt-BR',{roleLabel:e.target.value})}/></label><label className="wide"><span>Bio PT</span><textarea value={m.locales?.['pt-BR']?.bio||''} onChange={e=>patchMemberLocale(m.id,'pt-BR',{bio:e.target.value})}/></label><label><span>Cargo ES</span><input value={m.locales?.es?.roleLabel||''} onChange={e=>patchMemberLocale(m.id,'es',{roleLabel:e.target.value})}/></label><label className="wide"><span>Bio ES</span><textarea value={m.locales?.es?.bio||''} onChange={e=>patchMemberLocale(m.id,'es',{bio:e.target.value})}/></label></div></article>)}</div>:<Empty>Nenhuma pessoa cadastrada na equipe.</Empty>}
    </>}
    {tab==='freelancers'&&<>{freelancers.length?<div className="list">{freelancers.map(x=><article key={x.id}><div><strong>{x.name}</strong><span>{x.city}{x.state?' · '+x.state:''} · {x.whatsapp} · {x.status}</span></div><div className="row-actions"><select value={x.status} onChange={e=>updateFreelancer(x.id,e.target.value)}><option value="new">Novo</option><option value="reviewing">Em análise</option><option value="approved">Aprovado</option><option value="contacted">Contatado</option><option value="inactive">Inativo</option><option value="rejected">Recusado</option></select>{x.portfolio_url&&<a className="button" href={x.portfolio_url} target="_blank" rel="noreferrer">Portfólio</a>}{x.instagram&&<a className="button" href={x.instagram.startsWith('http')?x.instagram:`https://instagram.com/${x.instagram.replace('@','')}`} target="_blank" rel="noreferrer">Instagram</a>}</div></article>)}</div>:<Empty>Nenhum freelancer cadastrado ainda.</Empty>}</>}
  </Panel>;
}
