import { useEffect,useMemo,useState } from 'react';
import { api } from '../../lib/api';
import { Icon } from '../../components/Icons';
import { Badge,Notice,Panel } from '../../components/StateViews';

type Locale='pt-BR'|'es';
type CopyTab='interface'|'freelancerPage'|'partnershipPage'|'eventPage'|'popup';
type FieldDef={key:string;label:string;multiline?:boolean};

const chromeDefaults:any={
  metaTitlePt:'GTRZ Eventos',metaTitleEs:'GTRZ Eventos',
  metaDescriptionPt:'GTRZ Eventos — experiências culturais entre Venezuela e Brasil.',metaDescriptionEs:'GTRZ Eventos — experiencias culturales entre Venezuela y Brasil.',
  footerPt:'GTRZ Eventos · Venezuela → Brasil',footerEs:'GTRZ Eventos · Venezuela → Brasil',eventsLabelPt:'Eventos',eventsLabelEs:'Eventos',langShortPt:'PT',langShortEs:'ES',
  gateEyebrowPt:'Venezuela → Brasil',gateEyebrowEs:'Venezuela → Brasil',gateTitlePrefixPt:'COMO VOCÊ QUER',gateTitlePrefixEs:'¿CÓMO QUIERES',gateTitleHighlightPt:'ENTRAR?',gateTitleHighlightEs:'ENTRAR?',
  gateBodyPt:'Escolha o idioma da experiência.',gateBodyEs:'Elige el idioma de la experiencia.',gateHintPt:'Você pode mudar o idioma novamente no menu do site.',gateHintEs:'Puedes cambiar el idioma nuevamente en el menú.',gateOptionPt:'Português',gateOptionEs:'Español',
  navPt:[['Sobre','#sobre'],['Ritmos','#ritmos'],['Diferenciais','#diferenciais'],['Quem faz','#quem'],['Trabalhe conosco','#trabalhe'],['Parcerias','#parcerias'],['Instagram','#instagram']],
  navEs:[['Sobre','#sobre'],['Ritmos','#ritmos'],['Diferenciales','#diferenciais'],['Quiénes somos','#quem'],['Trabaja con nosotros','#trabalhe'],['Alianzas','#parcerias'],['Instagram','#instagram']]
};

const copyDefaults:Record<Locale,Record<string,Record<string,string>>>={
  'pt-BR':{
    freelancerPage:{seoTitle:'Trabalhe conosco — GTRZ',eyebrow:'GTRZ · FREELANCERS',title:'TRABALHE COM A GENTE.',intro:'Cadastre-se no nosso banco de profissionais para futuras produções. O cadastro não representa promessa de contratação.',nameLabel:'Nome completo',whatsappLabel:'WhatsApp',emailLabel:'E-mail',cityLabel:'Cidade',stateLabel:'Estado',instagramLabel:'Instagram',rolesLabel:'Áreas de atuação',rolesPlaceholder:'Produção, foto, bar, design...',portfolioLabel:'Portfólio',portfolioPlaceholder:'https://',availabilityLabel:'Disponibilidade / observações',submitLabel:'Enviar cadastro',successMessage:'Cadastro recebido. A GTRZ entrará em contato quando houver uma oportunidade compatível.',errorMessage:'Não foi possível enviar. Tente novamente.'},
    partnershipPage:{seoTitle:'Parcerias — GTRZ',eyebrow:'GTRZ · PARCERIAS',title:'VAMOS CONSTRUIR JUNTOS.',intro:'Casas, marcas, artistas, fornecedores e projetos que queiram construir uma experiência com a GTRZ.',contactNameLabel:'Seu nome',companyNameLabel:'Empresa / projeto',typeLabel:'Tipo de parceria',typePlaceholder:'—',venueOption:'Casa / espaço',brandOption:'Marca / patrocínio',artistOption:'Artista / projeto cultural',supplierOption:'Fornecedor',otherOption:'Outro',cityLabel:'Cidade',emailLabel:'E-mail',whatsappLabel:'WhatsApp',messageLabel:'Conte a ideia',submitLabel:'Enviar proposta',successMessage:'Proposta recebida. Nossa equipe vai analisar.',errorMessage:'Não foi possível enviar. Tente novamente.'},
    eventPage:{backLabel:'← GTRZ',dateLabel:'DATA',venueLabel:'LOCAL',aboutLabel:'Sobre o evento',lineupEyebrow:'GTRZ',lineupTitle:'LINE-UP.',ticketsEyebrow:'Ingressos',ticketsTitle:'ESCOLHA SEU INGRESSO.',availableLabel:'DISPONÍVEL',draftLabel:'EM BREVE',soldOutLabel:'ESGOTADO',closedLabel:'ENCERRADO',buyLabel:'Comprar',noTickets:'Os ingressos ainda não estão disponíveis.',notFoundTitle:'EVENTO NÃO ENCONTRADO.',notFoundCta:'GTRZ'},
    popup:{multiHeader:'Eventos GTRZ disponíveis',singleHeader:'Tem evento ativo na GTRZ',closeLabel:'Fechar',eyebrow:'Agenda aberta',multiTitleLine1:'TEM GTRZ',multiTitleLine2:'EM MAIS DE UMA',multiTitleAccent:'CIDADE.',singleTitleLine1:'TEM GTRZ',singleTitleLine2:'NA SUA',singleTitleAccent:'CIDADE.',multiBody:'Escolha a cidade e entre direto na página do evento.',singleFallbackBody:'Confira data, local e ingressos disponíveis.',soldOutLabel:'Esgotado',eventCta:'Ver evento e ingressos',continueLabel:'Continuar no institucional'}
  },
  es:{
    freelancerPage:{seoTitle:'Freelancers — GTRZ',eyebrow:'GTRZ · FREELANCERS',title:'TRABAJA CON NOSOTROS.',intro:'Regístrate en nuestra base de profesionales para futuras producciones. El registro no representa una promesa de contratación.',nameLabel:'Nombre completo',whatsappLabel:'WhatsApp',emailLabel:'E-mail',cityLabel:'Ciudad',stateLabel:'Estado',instagramLabel:'Instagram',rolesLabel:'Áreas de trabajo',rolesPlaceholder:'Producción, foto, bar, diseño...',portfolioLabel:'Portafolio',portfolioPlaceholder:'https://',availabilityLabel:'Disponibilidad / observaciones',submitLabel:'Enviar registro',successMessage:'Registro recibido. GTRZ se pondrá en contacto cuando exista una oportunidad compatible.',errorMessage:'No fue posible enviar. Inténtalo nuevamente.'},
    partnershipPage:{seoTitle:'Alianzas — GTRZ',eyebrow:'GTRZ · ALIANZAS',title:'CONSTRUYAMOS ALGO JUNTOS.',intro:'Espacios, marcas, artistas, proveedores y proyectos que quieran crear una experiencia con GTRZ.',contactNameLabel:'Tu nombre',companyNameLabel:'Empresa / proyecto',typeLabel:'Tipo de alianza',typePlaceholder:'—',venueOption:'Espacio / casa',brandOption:'Marca / patrocinio',artistOption:'Artista / proyecto cultural',supplierOption:'Proveedor',otherOption:'Otro',cityLabel:'Ciudad',emailLabel:'E-mail',whatsappLabel:'WhatsApp',messageLabel:'Cuéntanos la idea',submitLabel:'Enviar propuesta',successMessage:'Propuesta recibida. Nuestro equipo la revisará.',errorMessage:'No fue posible enviar. Inténtalo nuevamente.'},
    eventPage:{backLabel:'← GTRZ',dateLabel:'FECHA',venueLabel:'LUGAR',aboutLabel:'Sobre el evento',lineupEyebrow:'GTRZ',lineupTitle:'LINE-UP.',ticketsEyebrow:'Entradas',ticketsTitle:'ELIGE TU ENTRADA.',availableLabel:'DISPONIBLE',draftLabel:'PRÓXIMAMENTE',soldOutLabel:'AGOTADO',closedLabel:'CERRADO',buyLabel:'Comprar',noTickets:'Las entradas todavía no están disponibles.',notFoundTitle:'EVENTO NO ENCONTRADO.',notFoundCta:'GTRZ'},
    popup:{multiHeader:'Eventos GTRZ disponibles',singleHeader:'Hay un evento activo en GTRZ',closeLabel:'Cerrar',eyebrow:'Agenda abierta',multiTitleLine1:'HAY GTRZ',multiTitleLine2:'EN MÁS DE UNA',multiTitleAccent:'CIUDAD.',singleTitleLine1:'HAY GTRZ',singleTitleLine2:'EN TU',singleTitleAccent:'CIUDAD.',multiBody:'Elige la ciudad y entra directamente a la página del evento.',singleFallbackBody:'Consulta fecha, lugar y entradas disponibles.',soldOutLabel:'Agotado',eventCta:'Ver evento y entradas',continueLabel:'Continuar en el sitio institucional'}
  }
};

const groupFields:Record<Exclude<CopyTab,'interface'>,FieldDef[]>={
  freelancerPage:[
    {key:'seoTitle',label:'Título SEO'},{key:'eyebrow',label:'Linha de apoio'},{key:'title',label:'Título'},{key:'intro',label:'Texto de abertura',multiline:true},{key:'nameLabel',label:'Campo · nome'},{key:'whatsappLabel',label:'Campo · WhatsApp'},{key:'emailLabel',label:'Campo · e-mail'},{key:'cityLabel',label:'Campo · cidade'},{key:'stateLabel',label:'Campo · estado'},{key:'instagramLabel',label:'Campo · Instagram'},{key:'rolesLabel',label:'Campo · áreas'},{key:'rolesPlaceholder',label:'Placeholder · áreas'},{key:'portfolioLabel',label:'Campo · portfólio'},{key:'portfolioPlaceholder',label:'Placeholder · portfólio'},{key:'availabilityLabel',label:'Campo · disponibilidade'},{key:'submitLabel',label:'Botão de envio'},{key:'successMessage',label:'Mensagem de sucesso',multiline:true},{key:'errorMessage',label:'Mensagem de erro',multiline:true}
  ],
  partnershipPage:[
    {key:'seoTitle',label:'Título SEO'},{key:'eyebrow',label:'Linha de apoio'},{key:'title',label:'Título'},{key:'intro',label:'Texto de abertura',multiline:true},{key:'contactNameLabel',label:'Campo · nome'},{key:'companyNameLabel',label:'Campo · empresa/projeto'},{key:'typeLabel',label:'Campo · tipo'},{key:'typePlaceholder',label:'Opção vazia'},{key:'venueOption',label:'Opção · casa/espaço'},{key:'brandOption',label:'Opção · marca'},{key:'artistOption',label:'Opção · artista'},{key:'supplierOption',label:'Opção · fornecedor'},{key:'otherOption',label:'Opção · outro'},{key:'cityLabel',label:'Campo · cidade'},{key:'emailLabel',label:'Campo · e-mail'},{key:'whatsappLabel',label:'Campo · WhatsApp'},{key:'messageLabel',label:'Campo · mensagem'},{key:'submitLabel',label:'Botão de envio'},{key:'successMessage',label:'Mensagem de sucesso',multiline:true},{key:'errorMessage',label:'Mensagem de erro',multiline:true}
  ],
  eventPage:[
    {key:'backLabel',label:'Voltar'},{key:'dateLabel',label:'Rótulo · data'},{key:'venueLabel',label:'Rótulo · local'},{key:'aboutLabel',label:'Título · sobre'},{key:'lineupEyebrow',label:'Linha de apoio · line-up'},{key:'lineupTitle',label:'Título · line-up'},{key:'ticketsEyebrow',label:'Linha de apoio · ingressos'},{key:'ticketsTitle',label:'Título · ingressos'},{key:'availableLabel',label:'Status · disponível'},{key:'draftLabel',label:'Status · rascunho'},{key:'soldOutLabel',label:'Status · esgotado'},{key:'closedLabel',label:'Status · encerrado'},{key:'buyLabel',label:'Botão comprar'},{key:'noTickets',label:'Sem ingressos',multiline:true},{key:'notFoundTitle',label:'Evento não encontrado'},{key:'notFoundCta',label:'Botão do 404'}
  ],
  popup:[
    {key:'multiHeader',label:'Cabeçalho · vários eventos'},{key:'singleHeader',label:'Cabeçalho · um evento'},{key:'closeLabel',label:'Acessibilidade · fechar'},{key:'eyebrow',label:'Linha de apoio'},{key:'multiTitleLine1',label:'Título múltiplo · linha 1'},{key:'multiTitleLine2',label:'Título múltiplo · linha 2'},{key:'multiTitleAccent',label:'Título múltiplo · destaque'},{key:'singleTitleLine1',label:'Título único · linha 1'},{key:'singleTitleLine2',label:'Título único · linha 2'},{key:'singleTitleAccent',label:'Título único · destaque'},{key:'multiBody',label:'Texto · vários eventos',multiline:true},{key:'singleFallbackBody',label:'Texto padrão · um evento',multiline:true},{key:'soldOutLabel',label:'Status esgotado'},{key:'eventCta',label:'CTA do evento'},{key:'continueLabel',label:'Botão continuar'}
  ]
};

const interfaceFields=(locale:Locale):FieldDef[]=>locale==='pt-BR'?[{key:'metaTitlePt',label:'Título SEO'},{key:'metaDescriptionPt',label:'Descrição SEO',multiline:true},{key:'eventsLabelPt',label:'Botão Eventos'},{key:'footerPt',label:'Rodapé'},{key:'langShortPt',label:'Abreviação PT'},{key:'gateEyebrowPt',label:'Porta de idioma · linha de apoio'},{key:'gateTitlePrefixPt',label:'Porta · título'},{key:'gateTitleHighlightPt',label:'Porta · destaque'},{key:'gateBodyPt',label:'Porta · texto'},{key:'gateHintPt',label:'Porta · dica'},{key:'gateOptionPt',label:'Opção Português'}]:[{key:'metaTitleEs',label:'Título SEO'},{key:'metaDescriptionEs',label:'Descrição SEO',multiline:true},{key:'eventsLabelEs',label:'Botón Eventos'},{key:'footerEs',label:'Pie de página'},{key:'langShortEs',label:'Abreviação ES'},{key:'gateEyebrowEs',label:'Puerta de idioma · línea de apoyo'},{key:'gateTitlePrefixEs',label:'Puerta · título'},{key:'gateTitleHighlightEs',label:'Puerta · destaque'},{key:'gateBodyEs',label:'Puerta · texto'},{key:'gateHintEs',label:'Puerta · dica'},{key:'gateOptionEs',label:'Opción Español'}];

function safeParse(raw:string|undefined,fallback:any){try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function navText(value:any){return (Array.isArray(value)?value:[]).map((item:any)=>Array.isArray(item)?`${item[0]||''}|${item[1]||''}`:'').filter(Boolean).join('\n')}
function parseNav(value:string){return value.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [label,...rest]=line.split('|');return [label?.trim()||'',rest.join('|').trim()||'#']}).filter(([label])=>label)}

export function PublicCopy(){
  const [tab,setTab]=useState<CopyTab>('interface');
  const [chrome,setChrome]=useState<any>(chromeDefaults);const [copy,setCopy]=useState<any>(copyDefaults);
  const [navPt,setNavPt]=useState(navText(chromeDefaults.navPt));const [navEs,setNavEs]=useState(navText(chromeDefaults.navEs));
  const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  const load=async()=>{const r=await api<any>('/api/admin/settings');const rows=r.results||[];const ch=rows.find((x:any)=>x.key==='chrome');const cp=rows.find((x:any)=>x.key==='copy');const nextChrome={...chromeDefaults,...safeParse(ch?.value_json,{})};const stored=safeParse(cp?.value_json,{});const nextCopy:any={'pt-BR':{},es:{}};(['pt-BR','es'] as Locale[]).forEach(locale=>Object.keys(copyDefaults[locale]).forEach(group=>{nextCopy[locale][group]={...copyDefaults[locale][group],...(stored?.[locale]?.[group]||{})}}));setChrome(nextChrome);setCopy(nextCopy);setNavPt(navText(nextChrome.navPt));setNavEs(navText(nextChrome.navEs));};
  useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
  const save=async()=>{setBusy(true);setMessage('');try{if(tab==='interface')await api('/api/admin/settings/chrome',{method:'PUT',body:JSON.stringify({...chrome,navPt:parseNav(navPt),navEs:parseNav(navEs)})});else await api('/api/admin/settings/copy',{method:'PUT',body:JSON.stringify(copy)});setMessage('Textos publicados salvos.');await load();}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
  const updateCopy=(locale:Locale,group:string,key:string,value:string)=>setCopy((prev:any)=>({...prev,[locale]:{...prev[locale],[group]:{...prev[locale][group],[key]:value}}}));
  const tabTitle=useMemo(()=>({interface:'Interface global',freelancerPage:'Trabalhe conosco',partnershipPage:'Parcerias',eventPage:'Página de evento',popup:'Popup de eventos'}[tab]),[tab]);
  return <div className="module-stack"><Panel title="Textos do site" eyebrow="Editorial" description="Controle central dos textos públicos. A Home é editada em Conteúdo; aqui ficam interface global, páginas auxiliares, página de evento e popup. PT e ES são independentes." action={<button className="primary" onClick={save} disabled={busy}><Icon name="save" size={16}/>{busy?'Salvando…':'Salvar textos'}</button>}>
    <div className="segment-tabs"><button className={tab==='interface'?'active':''} onClick={()=>setTab('interface')}>Interface</button><button className={tab==='freelancerPage'?'active':''} onClick={()=>setTab('freelancerPage')}>Trabalhe conosco</button><button className={tab==='partnershipPage'?'active':''} onClick={()=>setTab('partnershipPage')}>Parcerias</button><button className={tab==='eventPage'?'active':''} onClick={()=>setTab('eventPage')}>Evento</button><button className={tab==='popup'?'active':''} onClick={()=>setTab('popup')}>Popup</button></div>
    <div className="editor-section-head"><div><small>EDIÇÃO BILÍNGUE</small><h3>{tabTitle}</h3></div><Badge tone="green">PT + ES</Badge></div>
    <div className="locale-grid">{(['pt-BR','es'] as Locale[]).map(locale=><section className="locale-editor" key={locale}><div className="locale-editor-head"><div><Badge tone="red">{locale==='pt-BR'?'PT':'ES'}</Badge><h4>{locale==='pt-BR'?'Português':'Español'}</h4></div><small>{tab==='interface'?interfaceFields(locale).length:groupFields[tab].length} textos</small></div>{(tab==='interface'?interfaceFields(locale):groupFields[tab]).map(field=><label className="field" key={field.key}><span>{field.label}</span>{field.multiline?<textarea value={tab==='interface'?(chrome[field.key]||''):(copy[locale]?.[tab]?.[field.key]||'')} onChange={e=>tab==='interface'?setChrome((v:any)=>({...v,[field.key]:e.target.value})):updateCopy(locale,tab,field.key,e.target.value)}/>:<input value={tab==='interface'?(chrome[field.key]||''):(copy[locale]?.[tab]?.[field.key]||'')} onChange={e=>tab==='interface'?setChrome((v:any)=>({...v,[field.key]:e.target.value})):updateCopy(locale,tab,field.key,e.target.value)}/>}</label>)}{tab==='interface'&&<label className="field"><span>{locale==='pt-BR'?'Menu PT':'Menú ES'}</span><textarea className="code-editor compact" value={locale==='pt-BR'?navPt:navEs} onChange={e=>locale==='pt-BR'?setNavPt(e.target.value):setNavEs(e.target.value)}/><small>Nome|#ancora · uma linha por item</small></label>}</section>)}</div>
    {message&&<Notice tone={message.toLowerCase().includes('erro')||message.toLowerCase().includes('error')?'error':'success'}>{message}</Notice>}
  </Panel></div>;
}
